## palette

palette = "catppuccin_mocha"

### theme

##====================================================================================================================##

################################
### Pastel Powerline Preset  ###
################################

## start
# format = """
# [](#9A348E)\
# $os\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#1FA0F0)\
# $git_branch\
# $git_status\
# [](fg:#1FA0F0 bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [](#33658A)
# [ ](fg:#58F08A)\
# """
#
# # Disable the blank line at the start of the prompt
# add_newline = true
#
# # You can also replace your username with a neat symbol like   or disable this
# # and use the os module below
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
# disabled = true
#
# # An alternative to the username module which displays a symbol that
# # represents the current operating system
# [os]
# style = "bg:#9A348E"
# disabled = false # Disabled by default
#
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = " 󰈙 "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important 󰈙 " = " 󰈙 "
#
# [c]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style) $path'
#
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [git_branch]
# symbol = ""
# style = "bg:#1FA0F0"
# format = '[ $symbol $branch ]($style)'
#
# [git_status]
# style = "bg:#1FA0F0"
# format = '[$all_status$ahead_behind ]($style)'
#
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [gradle]
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [haskell]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [nim]
# symbol = "󰆥 "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [scala]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ♥ $time ]($style)'
#
#

## end


##====================================================================================================================##

################################
### Nerd Font Symbols Preset ###
################################

## start

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style))'
ignore_submodules = true # Please check https://github.com/starship/starship/issues/4305
# conflicted = "[](red)[$count](bold red)"
# ahead = '[⇡](green)[${count}](bold green)'
# diverged = '[⇕⇡](yellow)[${ahead_count}](bold yellow)[⇣](yellow)[${behind_count}](bold yellow)'
# behind = '[⇣](green)[${count}](bold green)'
# # up_to_date = " 󰄴"
# untracked = "[󱀶](cyan)[$count](bold cyan)"
# stashed = "[󰏔](yellow)[$count](bold yellow)"
# modified = "[](yellow)[$count](bold yellow) "
# staged = "[󱧕](blue)[$count](bold blue)"
# renamed = "[󰾴](green)[$count](bold green)"
# deleted = "[󰧧](red)[$count](bold red)"
conflicted = "[](red)[$count](bold red) "
ahead = "[⇡](green)[${count}](bold green) "
diverged = "[⇕⇡](yellow)[${ahead_count}](bold yellow)[⇣](yellow)[${behind_count}](bold yellow) "
behind = "[⇣](green)[${count}](bold green) "
# up_to_date = " 󰄴"
untracked = "[?$count](bold cyan) "
stashed = "[󰏔](yellow)[$count](bold yellow) "
modified = "[!$count](bold yellow) "
staged = "[󱧕](blue)[$count](bold blue) "
renamed = "[󰾴](green)[$count](bold green) "
deleted = "[󰧧](red)[$count](bold red) "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\( $virtualenv\) )]($style)'
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
